Repository stackblitz-labs/bolt.diy, pull requests merged in 2024-12, with the labels that each got.

#520 doc: Issue Template Update
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: documentation, enhancement

#483 [feat]: Implement chat description editing in sidebar and header, add…
  app/components/header/Header.tsx
  app/components/sidebar/HistoryItem.tsx
  app/lib/hooks/index.ts
  app/lib/hooks/useEditChatDescription.ts
  app/lib/persistence/ChatDescription.client.tsx
  app/lib/persistence/db.ts
  app/lib/runtime/action-runner.ts
Labels: enhancement, ui-enhancement

#332 HIGH PRIORITY - Attach images to prompts
  app/components/chat/BaseChat.tsx
  app/components/chat/Chat.client.tsx
  app/components/chat/FilePreview.tsx
  app/components/chat/SendButton.client.tsx
  app/components/chat/UserMessage.tsx
  app/components/sidebar/Menu.client.tsx
  app/lib/.server/llm/model.ts
  app/lib/.server/llm/stream-text.ts
  app/lib/stores/files.ts
  app/routes/api.chat.ts
  app/utils/logger.ts
  vite.config.ts
Labels: enhancement, question, WIP

#421 feat(git): Git Repository Integration
  .husky/pre-commit
  app/components/chat/Artifact.tsx
  app/components/chat/BaseChat.tsx
  app/components/chat/GitCloneButton.tsx
  app/components/chat/chatExportAndImport/ImportButtons.tsx
  app/lib/hooks/useGit.ts
  package.json
  pnpm-lock.yaml
Labels: enhancement

#580 feat: Added a tabbed setting modal
  .github/workflows/commit.yaml
  app/commit.json
  app/components/chat/BaseChat.tsx
  app/components/chat/ModelSelector.tsx
  app/components/sidebar/Menu.client.tsx
  app/components/ui/Settings.tsx
  app/components/ui/SettingsButton.tsx
  app/components/ui/SettingsSlider.tsx
  app/lib/stores/settings.ts
  app/types/model.ts
Labels: enhancement

#565 ui: Update the model collapse button
  app/components/chat/BaseChat.tsx
  app/components/chat/SendButton.client.tsx
Labels: ui-enhancement

#426 Refinement of folder import
  app/components/chat/ImportFolderButton.tsx
  app/utils/fileUtils.ts
  app/utils/folderImport.ts
Labels: enhancement

#592 ui/settings style
  app/components/ui/Settings.tsx
  app/components/ui/SettingsSlider.tsx
  app/styles/components/Settings.scss
  app/styles/components/SettingsSlider.scss
Labels: ui-enhancement

#282 feat(styling): added ray effects for the UI as decorative elements
  app/components/chat/BaseChat.module.scss
  app/components/chat/BaseChat.tsx
  app/components/header/Header.tsx
  app/components/ui/BackgroundRays/index.tsx
  app/components/ui/BackgroundRays/styles.module.scss
  app/routes/_index.tsx
  app/styles/index.scss
  uno.config.ts
Labels: enhancement

#688 chore: Add Automated Release Workflow
  .github/workflows/update-stable.yml
  package.json
Labels: stable-release

#689 chore: fix versioning workflow
  .github/workflows/update-stable.yml
Labels: stable-release

#690 fix: the creds issue in workflow
  .github/workflows/update-stable.yml
Labels: stable-release

#691 chore: fix workflow permission
  .github/workflows/update-stable.yml
Labels: stable-release

#692 chore: Versioning workflow
  .github/workflows/update-stable.yml
  app/commit.json
Labels: stable-release

#695 chore: Versioning workflow fix
  .github/workflows/update-stable.yml
Labels: stable-release

#696 chore: added workflow permission
  .github/workflows/update-stable.yml
Labels: stable-release

#697 docs: added socials
  .github/workflows/update-stable.yml
  docs/mkdocs.yml
Labels: stable-release

#701 chore: Adding workflow
  .github/workflows/pr-release-validation.yaml
  .github/workflows/update-stable.yml
Labels: stable-release

#702 chore: skipping commit version
  .github/workflows/commit.yaml
  .github/workflows/update-stable.yml
Labels: stable-release

#643 doc: update README.md
  README.md
Labels: documentation

#602 Feat: Basic file tree context menu
  app/components/workbench/FileTree.tsx
  package.json
  pnpm-lock.yaml
Labels: enhancement

#739 ui: fallback icon for provider
  app/components/settings/providers/ProvidersTab.tsx
Labels: ui-enhancement

#727 ui-ux: debug tab
  app/components/settings/debug/DebugTab.tsx
  app/components/settings/features/FeaturesTab.tsx
  app/lib/hooks/useSettings.tsx
  app/lib/stores/settings.ts
Labels: ui-enhancement

#433 Check the render method of SlotClone. #432
  app/components/chat/Messages.client.tsx
  app/components/ui/IconButton.tsx
  app/components/ui/Tooltip.tsx
Labels: enhancement, pr-ready-to-merge

#776 release: Bugfix for stable
  .github/workflows/commit.yaml
  .github/workflows/update-stable.yml
  app/commit.json
  app/components/settings/connections/ConnectionsTab.tsx
  app/components/settings/features/FeaturesTab.tsx
  app/components/sidebar/HistoryItem.tsx
  app/lib/runtime/action-runner.ts
Labels: stable-release

#784 fix: prompt enhance fixed
  app/routes/api.enhancer.ts
Labels: stable-release

#817 docs: simplified setup
  README.md
Labels: documentation

#794 docs: added a toc for the readme
  README.md
Labels: documentation

#805 feat: improved providers list style
  app/components/settings/providers/ProvidersTab.tsx
Labels: ui-enhancement

#845 docs: updated Docs
  CONTRIBUTING.md
  FAQ.md
  README.md
  docs/docs/CONTRIBUTING.md
  docs/docs/index.md
Labels: documentation

#803 feat: data tab
  app/components/settings/SettingsWindow.tsx
  app/components/settings/chat-history/ChatHistoryTab.tsx
  app/components/settings/data/DataTab.tsx
Labels: ui-enhancement

#895 fix: updated logger and model caching minor bugfix #release
  app/components/chat/BaseChat.tsx
  app/components/chat/Chat.client.tsx
  app/components/settings/providers/ProvidersTab.tsx
  app/entry.server.tsx
  app/lib/.server/llm/stream-text.ts
  app/lib/modules/llm/base-provider.ts
  app/lib/modules/llm/manager.ts
  app/lib/modules/llm/providers/huggingface.ts
  app/lib/modules/llm/providers/hyperbolic.ts
  app/lib/modules/llm/providers/lmstudio.ts
  app/lib/modules/llm/providers/ollama.ts
  app/lib/modules/llm/providers/open-router.ts
  app/lib/modules/llm/providers/openai-like.ts
  app/lib/modules/llm/providers/openai.ts
  app/lib/modules/llm/providers/together.ts
  app/lib/runtime/message-parser.ts
  app/lib/stores/settings.ts
  app/routes/api.chat.ts
  app/utils/constants.ts
  app/utils/logger.ts
  app/utils/selectStarterTemplate.ts
  package.json
  pnpm-lock.yaml
Labels: stable-release

#959 fix: hotfix auto select starter template works without github token #release
  .github/scripts/generate-changelog.sh
  .github/workflows/update-stable.yml
  app/utils/selectStarterTemplate.ts
Labels: stable-release
