Repository stackblitz-labs/bolt.diy, pull requests merged in 2025-01, with the labels that each got.

#274 fix: added XAI to docker config
  Dockerfile
  docker-compose.yaml
Labels: enhancement

#1101 feat: added the "Open Preview in a New Tab"
  app/components/workbench/Preview.tsx
  app/lib/stores/previews.ts
  app/routes/webcontainer.preview.$id.tsx
Labels: ui-enhancement

#1108 feat: configure dynamic providers via .env
  app/components/chat/BaseChat.tsx
  app/lib/api/cookies.ts
  app/lib/modules/llm/manager.ts
  app/routes/api.enhancer.ts
  app/routes/api.llmcall.ts
  app/routes/api.models.$provider.ts
  app/routes/api.models.ts
  app/utils/constants.ts
Labels: epic:llm

#1091 feat: enhance context handling by adding code context selection and implementing summary generation
  app/components/chat/AssistantMessage.tsx
  app/components/ui/Popover.tsx
  app/entry.server.tsx
  app/lib/.server/llm/constants.ts
  app/lib/.server/llm/create-summary.ts
  app/lib/.server/llm/select-context.ts
  app/lib/.server/llm/stream-text.ts
  app/lib/.server/llm/utils.ts
  app/lib/modules/llm/base-provider.ts
  app/routes/api.chat.ts
  app/routes/api.enhancer.ts
  app/routes/api.llmcall.ts
  app/styles/variables.scss
  app/types/context.ts
  package.json
  pnpm-lock.yaml
Labels: stable-release
